name: Events Demo One
on:
  pull_request:
    types: 
      - opened
    branches:
      - staging
      - 'staging-*' # for ex. staging-new
  workflow_dispatch:
  push:
    branches:
      - staging
      - 'staging-*' # for ex. staging-new
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [download] code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm install --force
      - name: Run Unit Tests
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deployed..."